[workspace]
resolver = "2"
members = [
	"hercules_cg",
	"hercules_ir",
	"hercules_opt",
	"hercules_rt",

	"hercules_tools/hercules_dot",
	"hercules_tools/hercules_cpu",

  "frontend",

	"hercules_samples/matmul"
]
