[workspace]

members = [
	"hercules_cg",
	"hercules_ir",
	"hercules_opt",
	"hercules_rt",

	"hercules_tools/hercules_driver",
	"hercules_tools/hercules_dot",
	"hercules_tools/hercules_cpu_beta",

	"hercules_samples/matmul"
]
