[package]
name = "hercules_matmul"
version = "0.1.0"
authors = ["Russel Arbore <rarbore2@illinois.edu>"]

[dependencies]
clap = { version = "*", features = ["derive"] }
hercules_rt = { path = "../../hercules_rt" }
rand = "*"
